/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWalletRouteImport } from './routes/_app.wallet'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppLearnRouteImport } from './routes/_app.learn'
import { Route as AppFeedRouteImport } from './routes/_app.feed'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppVideoIndexRouteImport } from './routes/_app.video.index'
import { Route as AppPartnersIndexRouteImport } from './routes/_app.partners.index'
import { Route as AppEcosystemIndexRouteImport } from './routes/_app.ecosystem.index'
import { Route as AppChatsIndexRouteImport } from './routes/_app.chats.index'
import { Route as AppVideoVideoIdRouteImport } from './routes/_app.video.$videoId'
import { Route as AppSandboxUsernameRouteImport } from './routes/_app.sandbox.$username'
import { Route as AppPartnersSlugRouteImport } from './routes/_app.partners.$slug'
import { Route as AppEcosystemAppIdRouteImport } from './routes/_app.ecosystem.$appId'
import { Route as AppChatsChatIdRouteImport } from './routes/_app.chats.$chatId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppVideoIndexRoute = AppVideoIndexRouteImport.update({
  id: '/video/',
  path: '/video/',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersIndexRoute = AppPartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => AppRoute,
} as any)
const AppEcosystemIndexRoute = AppEcosystemIndexRouteImport.update({
  id: '/ecosystem/',
  path: '/ecosystem/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsIndexRoute = AppChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AppRoute,
} as any)
const AppVideoVideoIdRoute = AppVideoVideoIdRouteImport.update({
  id: '/video/$videoId',
  path: '/video/$videoId',
  getParentRoute: () => AppRoute,
} as any)
const AppSandboxUsernameRoute = AppSandboxUsernameRouteImport.update({
  id: '/sandbox/$username',
  path: '/sandbox/$username',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersSlugRoute = AppPartnersSlugRouteImport.update({
  id: '/partners/$slug',
  path: '/partners/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppEcosystemAppIdRoute = AppEcosystemAppIdRouteImport.update({
  id: '/ecosystem/$appId',
  path: '/ecosystem/$appId',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsChatIdRoute = AppChatsChatIdRouteImport.update({
  id: '/chats/$chatId',
  path: '/chats/$chatId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/feed': typeof AppFeedRoute
  '/learn': typeof AppLearnRoute
  '/profile': typeof AppProfileRoute
  '/wallet': typeof AppWalletRoute
  '/chats/$chatId': typeof AppChatsChatIdRoute
  '/ecosystem/$appId': typeof AppEcosystemAppIdRoute
  '/partners/$slug': typeof AppPartnersSlugRoute
  '/sandbox/$username': typeof AppSandboxUsernameRoute
  '/video/$videoId': typeof AppVideoVideoIdRoute
  '/chats/': typeof AppChatsIndexRoute
  '/ecosystem/': typeof AppEcosystemIndexRoute
  '/partners/': typeof AppPartnersIndexRoute
  '/video/': typeof AppVideoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/feed': typeof AppFeedRoute
  '/learn': typeof AppLearnRoute
  '/profile': typeof AppProfileRoute
  '/wallet': typeof AppWalletRoute
  '/chats/$chatId': typeof AppChatsChatIdRoute
  '/ecosystem/$appId': typeof AppEcosystemAppIdRoute
  '/partners/$slug': typeof AppPartnersSlugRoute
  '/sandbox/$username': typeof AppSandboxUsernameRoute
  '/video/$videoId': typeof AppVideoVideoIdRoute
  '/chats': typeof AppChatsIndexRoute
  '/ecosystem': typeof AppEcosystemIndexRoute
  '/partners': typeof AppPartnersIndexRoute
  '/video': typeof AppVideoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/learn': typeof AppLearnRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/chats/$chatId': typeof AppChatsChatIdRoute
  '/_app/ecosystem/$appId': typeof AppEcosystemAppIdRoute
  '/_app/partners/$slug': typeof AppPartnersSlugRoute
  '/_app/sandbox/$username': typeof AppSandboxUsernameRoute
  '/_app/video/$videoId': typeof AppVideoVideoIdRoute
  '/_app/chats/': typeof AppChatsIndexRoute
  '/_app/ecosystem/': typeof AppEcosystemIndexRoute
  '/_app/partners/': typeof AppPartnersIndexRoute
  '/_app/video/': typeof AppVideoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/feed'
    | '/learn'
    | '/profile'
    | '/wallet'
    | '/chats/$chatId'
    | '/ecosystem/$appId'
    | '/partners/$slug'
    | '/sandbox/$username'
    | '/video/$videoId'
    | '/chats/'
    | '/ecosystem/'
    | '/partners/'
    | '/video/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/feed'
    | '/learn'
    | '/profile'
    | '/wallet'
    | '/chats/$chatId'
    | '/ecosystem/$appId'
    | '/partners/$slug'
    | '/sandbox/$username'
    | '/video/$videoId'
    | '/chats'
    | '/ecosystem'
    | '/partners'
    | '/video'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/feed'
    | '/_app/learn'
    | '/_app/profile'
    | '/_app/wallet'
    | '/_app/chats/$chatId'
    | '/_app/ecosystem/$appId'
    | '/_app/partners/$slug'
    | '/_app/sandbox/$username'
    | '/_app/video/$videoId'
    | '/_app/chats/'
    | '/_app/ecosystem/'
    | '/_app/partners/'
    | '/_app/video/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn': {
      id: '/_app/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/video/': {
      id: '/_app/video/'
      path: '/video'
      fullPath: '/video/'
      preLoaderRoute: typeof AppVideoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners/': {
      id: '/_app/partners/'
      path: '/partners'
      fullPath: '/partners/'
      preLoaderRoute: typeof AppPartnersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ecosystem/': {
      id: '/_app/ecosystem/'
      path: '/ecosystem'
      fullPath: '/ecosystem/'
      preLoaderRoute: typeof AppEcosystemIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats/': {
      id: '/_app/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AppChatsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/video/$videoId': {
      id: '/_app/video/$videoId'
      path: '/video/$videoId'
      fullPath: '/video/$videoId'
      preLoaderRoute: typeof AppVideoVideoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sandbox/$username': {
      id: '/_app/sandbox/$username'
      path: '/sandbox/$username'
      fullPath: '/sandbox/$username'
      preLoaderRoute: typeof AppSandboxUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners/$slug': {
      id: '/_app/partners/$slug'
      path: '/partners/$slug'
      fullPath: '/partners/$slug'
      preLoaderRoute: typeof AppPartnersSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ecosystem/$appId': {
      id: '/_app/ecosystem/$appId'
      path: '/ecosystem/$appId'
      fullPath: '/ecosystem/$appId'
      preLoaderRoute: typeof AppEcosystemAppIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats/$chatId': {
      id: '/_app/chats/$chatId'
      path: '/chats/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof AppChatsChatIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppFeedRoute: typeof AppFeedRoute
  AppLearnRoute: typeof AppLearnRoute
  AppProfileRoute: typeof AppProfileRoute
  AppWalletRoute: typeof AppWalletRoute
  AppChatsChatIdRoute: typeof AppChatsChatIdRoute
  AppEcosystemAppIdRoute: typeof AppEcosystemAppIdRoute
  AppPartnersSlugRoute: typeof AppPartnersSlugRoute
  AppSandboxUsernameRoute: typeof AppSandboxUsernameRoute
  AppVideoVideoIdRoute: typeof AppVideoVideoIdRoute
  AppChatsIndexRoute: typeof AppChatsIndexRoute
  AppEcosystemIndexRoute: typeof AppEcosystemIndexRoute
  AppPartnersIndexRoute: typeof AppPartnersIndexRoute
  AppVideoIndexRoute: typeof AppVideoIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppFeedRoute: AppFeedRoute,
  AppLearnRoute: AppLearnRoute,
  AppProfileRoute: AppProfileRoute,
  AppWalletRoute: AppWalletRoute,
  AppChatsChatIdRoute: AppChatsChatIdRoute,
  AppEcosystemAppIdRoute: AppEcosystemAppIdRoute,
  AppPartnersSlugRoute: AppPartnersSlugRoute,
  AppSandboxUsernameRoute: AppSandboxUsernameRoute,
  AppVideoVideoIdRoute: AppVideoVideoIdRoute,
  AppChatsIndexRoute: AppChatsIndexRoute,
  AppEcosystemIndexRoute: AppEcosystemIndexRoute,
  AppPartnersIndexRoute: AppPartnersIndexRoute,
  AppVideoIndexRoute: AppVideoIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
