/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWalletRouteImport } from './routes/_app.wallet'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppLearnRouteImport } from './routes/_app.learn'
import { Route as AppFeedRouteImport } from './routes/_app.feed'
import { Route as AppEcosystemRouteImport } from './routes/_app.ecosystem'
import { Route as AppChatsRouteImport } from './routes/_app.chats'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppSandboxUsernameRouteImport } from './routes/_app.sandbox.$username'
import { Route as AppEcosystemAppIdRouteImport } from './routes/_app.ecosystem.$appId'
import { Route as AppChatsChatIdRouteImport } from './routes/_app.chats.$chatId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppEcosystemRoute = AppEcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsRoute = AppChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSandboxUsernameRoute = AppSandboxUsernameRouteImport.update({
  id: '/sandbox/$username',
  path: '/sandbox/$username',
  getParentRoute: () => AppRoute,
} as any)
const AppEcosystemAppIdRoute = AppEcosystemAppIdRouteImport.update({
  id: '/$appId',
  path: '/$appId',
  getParentRoute: () => AppEcosystemRoute,
} as any)
const AppChatsChatIdRoute = AppChatsChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AppChatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/chats': typeof AppChatsRouteWithChildren
  '/ecosystem': typeof AppEcosystemRouteWithChildren
  '/feed': typeof AppFeedRoute
  '/learn': typeof AppLearnRoute
  '/profile': typeof AppProfileRoute
  '/wallet': typeof AppWalletRoute
  '/chats/$chatId': typeof AppChatsChatIdRoute
  '/ecosystem/$appId': typeof AppEcosystemAppIdRoute
  '/sandbox/$username': typeof AppSandboxUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/chats': typeof AppChatsRouteWithChildren
  '/ecosystem': typeof AppEcosystemRouteWithChildren
  '/feed': typeof AppFeedRoute
  '/learn': typeof AppLearnRoute
  '/profile': typeof AppProfileRoute
  '/wallet': typeof AppWalletRoute
  '/chats/$chatId': typeof AppChatsChatIdRoute
  '/ecosystem/$appId': typeof AppEcosystemAppIdRoute
  '/sandbox/$username': typeof AppSandboxUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/chats': typeof AppChatsRouteWithChildren
  '/_app/ecosystem': typeof AppEcosystemRouteWithChildren
  '/_app/feed': typeof AppFeedRoute
  '/_app/learn': typeof AppLearnRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/chats/$chatId': typeof AppChatsChatIdRoute
  '/_app/ecosystem/$appId': typeof AppEcosystemAppIdRoute
  '/_app/sandbox/$username': typeof AppSandboxUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/chats'
    | '/ecosystem'
    | '/feed'
    | '/learn'
    | '/profile'
    | '/wallet'
    | '/chats/$chatId'
    | '/ecosystem/$appId'
    | '/sandbox/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/chats'
    | '/ecosystem'
    | '/feed'
    | '/learn'
    | '/profile'
    | '/wallet'
    | '/chats/$chatId'
    | '/ecosystem/$appId'
    | '/sandbox/$username'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/chats'
    | '/_app/ecosystem'
    | '/_app/feed'
    | '/_app/learn'
    | '/_app/profile'
    | '/_app/wallet'
    | '/_app/chats/$chatId'
    | '/_app/ecosystem/$appId'
    | '/_app/sandbox/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn': {
      id: '/_app/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ecosystem': {
      id: '/_app/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof AppEcosystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats': {
      id: '/_app/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AppChatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sandbox/$username': {
      id: '/_app/sandbox/$username'
      path: '/sandbox/$username'
      fullPath: '/sandbox/$username'
      preLoaderRoute: typeof AppSandboxUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ecosystem/$appId': {
      id: '/_app/ecosystem/$appId'
      path: '/$appId'
      fullPath: '/ecosystem/$appId'
      preLoaderRoute: typeof AppEcosystemAppIdRouteImport
      parentRoute: typeof AppEcosystemRoute
    }
    '/_app/chats/$chatId': {
      id: '/_app/chats/$chatId'
      path: '/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof AppChatsChatIdRouteImport
      parentRoute: typeof AppChatsRoute
    }
  }
}

interface AppChatsRouteChildren {
  AppChatsChatIdRoute: typeof AppChatsChatIdRoute
}

const AppChatsRouteChildren: AppChatsRouteChildren = {
  AppChatsChatIdRoute: AppChatsChatIdRoute,
}

const AppChatsRouteWithChildren = AppChatsRoute._addFileChildren(
  AppChatsRouteChildren,
)

interface AppEcosystemRouteChildren {
  AppEcosystemAppIdRoute: typeof AppEcosystemAppIdRoute
}

const AppEcosystemRouteChildren: AppEcosystemRouteChildren = {
  AppEcosystemAppIdRoute: AppEcosystemAppIdRoute,
}

const AppEcosystemRouteWithChildren = AppEcosystemRoute._addFileChildren(
  AppEcosystemRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppChatsRoute: typeof AppChatsRouteWithChildren
  AppEcosystemRoute: typeof AppEcosystemRouteWithChildren
  AppFeedRoute: typeof AppFeedRoute
  AppLearnRoute: typeof AppLearnRoute
  AppProfileRoute: typeof AppProfileRoute
  AppWalletRoute: typeof AppWalletRoute
  AppSandboxUsernameRoute: typeof AppSandboxUsernameRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppChatsRoute: AppChatsRouteWithChildren,
  AppEcosystemRoute: AppEcosystemRouteWithChildren,
  AppFeedRoute: AppFeedRoute,
  AppLearnRoute: AppLearnRoute,
  AppProfileRoute: AppProfileRoute,
  AppWalletRoute: AppWalletRoute,
  AppSandboxUsernameRoute: AppSandboxUsernameRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
